"""Core data types, exceptions, and utilities for HTMA."""

from htma.core.exceptions import (
    AbstractionError,
    ConfigurationError,
    ConflictResolutionError,
    ConsolidationError,
    CuratorError,
    DatabaseConnectionError,
    DatabaseError,
    DuplicateMemoryError,
    ExtractionError,
    HTMAError,
    LinkMaintenanceError,
    LLMConnectionError,
    LLMError,
    LLMResponseError,
    LLMTimeoutError,
    MemoryError,
    MemoryNotFoundError,
    MemoryPressureError,
    MigrationError,
    ModelNotFoundError,
    PatternDetectionError,
    SalienceEvaluationError,
    StorageError,
    TemporalValidationError,
    ValidationError,
    VectorStoreError,
)
from htma.core.types import (
    BiTemporalRecord,
    Entity,
    EntityID,
    Episode,
    EpisodeID,
    EpisodeLink,
    Fact,
    FactID,
    MemoryNote,
    RetrievalResult,
    TemporalFilter,
    TemporalRange,
)
from htma.core.utils import (
    ensure_utc,
    generate_community_id,
    generate_entity_id,
    generate_episode_id,
    generate_fact_id,
    generate_link_id,
    is_valid_id,
    utc_now,
)

__all__ = [
    # Types
    "EntityID",
    "FactID",
    "EpisodeID",
    "TemporalRange",
    "BiTemporalRecord",
    "Entity",
    "Fact",
    "Episode",
    "EpisodeLink",
    "MemoryNote",
    "TemporalFilter",
    "RetrievalResult",
    # Exceptions
    "HTMAError",
    "MemoryError",
    "MemoryNotFoundError",
    "DuplicateMemoryError",
    "MemoryPressureError",
    "StorageError",
    "DatabaseError",
    "DatabaseConnectionError",
    "MigrationError",
    "VectorStoreError",
    "CuratorError",
    "SalienceEvaluationError",
    "ExtractionError",
    "ConflictResolutionError",
    "LLMError",
    "LLMConnectionError",
    "LLMTimeoutError",
    "LLMResponseError",
    "ModelNotFoundError",
    "ConsolidationError",
    "AbstractionError",
    "PatternDetectionError",
    "LinkMaintenanceError",
    "ValidationError",
    "TemporalValidationError",
    "ConfigurationError",
    # Utils
    "generate_entity_id",
    "generate_fact_id",
    "generate_episode_id",
    "generate_link_id",
    "generate_community_id",
    "utc_now",
    "ensure_utc",
    "is_valid_id",
]
